const players = [
    {
      "name": "Messi",
      "team": "images/miami.webp",
      "nationality": "images/argentina1.webp",
      "rating": 93,
      "pace": 85,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 38,
      "physicality": 65,
      "position": "RW",
      "photo": "images/messi.webp"
  },
  {
      "name": "Cristiano Ronaldo",
      "team": "images/alnasr.png",
      "nationality": "images/portugal.png",
      "rating": 94,
      "pace": 87,
      "shooting": 93,
      "passing": 81,
      "dribbling": 85,
      "defending": 34,
      "physicality": 75,
      "position": "ST",
      "photo": "images/ronaldo.webp"
  },
  {
      "name": "Mbappé",
      "team": "images/real1.svg",
      "nationality": "images/francie.png",
      "rating": 91,
      "pace": 97,
      "shooting": 88,
      "passing": 80,
      "dribbling": 92,
      "defending": 36,
      "physicality": 76,
      "position": "RW",
      "photo": "images/mbappe.png"
  },
  {
      "name": "Kevin De Bruyne",
      "team": "images/city.png",
      "nationality": "images/belgie.jpg",
      "rating": 91,
      "pace": 74,
      "shooting": 86,
      "passing": 94,
      "dribbling": 85,
      "defending": 64,
      "physicality": 74,
      "position": "CM",
      "photo": "images/kevin1.webp"
  },
  {
      "name": "Robert Lewandowski",
      "team": "images/barca.png",
      "nationality": "images/polsko.jpg",
      "rating": 92,
      "pace": 78,
      "shooting": 91,
      "passing": 78,
      "dribbling": 85,
      "defending": 44,
      "physicality": 82,
      "position": "ST",
      "photo": "images/lewa.png"
  },
  {
      "name": "Neymar Jr.",
      "team": "images/hilal.png",
      "nationality": "images/brazil.png",
      "rating": 89,
      "pace": 87,
      "shooting": 83,
      "passing": 85,
      "dribbling": 94,
      "defending": 37,
      "physicality": 60,
      "position": "LW",
      "photo": "images/neymar.webp"
  },


  {
    "name": "Sadio Mané",
    "team": "images/alnasr.png",
    "nationality": "images/senegal2.png",
    "rating": 89,
    "pace": 89,
    "shooting": 84,
    "passing": 78,
    "dribbling": 87,
    "defending": 45,
    "physicality": 81,
    "position": "LW",
    "photo": "images/mane.webp"
},
{
    "name": "Son Heung-min",
    "team": "images/spurs.png",
    "nationality": "images/korea2.png",
    "rating": 88,
    "pace": 86,
    "shooting": 85,
    "passing": 80,
    "dribbling": 89,
    "defending": 41,
    "physicality": 72,
    "position": "LW",   
    "photo": "images/son.png"
},
{
    "name": "Jack Grealish",
    "team": "images/city.png",
    "nationality": "images/anglie.webp",
    "rating": 85,
    "pace": 75,
    "shooting": 78,
    "passing": 85,
    "dribbling": 87,
    "defending": 50,
    "physicality": 70,
    "position": "LW",
    "photo": "images/grealish.png"
},
{
    "name": "Erling Haaland",
    "team": "images/city.png",
    "nationality": "images/norsko.png",
    "rating": 91,
    "pace": 84,
    "shooting": 94,
    "passing": 75,
    "dribbling": 80,
    "defending": 47,
    "physicality": 90,
    "position": "ST",
    "photo": "images/haaland.png"
},
{
    "name": "Harry Kane",
    "team": "images/bayern.png",
    "nationality": "images/anglie.webp",
    "rating": 91,
    "pace": 74,
    "shooting": 93,
    "passing": 79,
    "dribbling": 77,
    "defending": 40,
    "physicality": 85,
    "position": "ST",
    "photo": "images/kane.png"
},
{
    "name": "Karim Benzema",
    "team": "images/itihad.png",
    "nationality": "images/francie.png",
    "rating": 90,
    "pace": 74,
    "shooting": 91,
    "passing": 79,
    "dribbling": 85,
    "defending": 42,
    "physicality": 80,
    "position": "ST",
    "photo": "images/benzema.png"
},

{
    "name": "Mohamed Salah",
    "team": "images/liverpool.webp",
    "nationality": "images/egypt.webp",
    "rating": 90,
    "pace": 91,
    "shooting": 88,
    "passing": 81,
    "dribbling": 89,
    "defending": 45,
    "physicality": 78,
    "position": "RW",
    "photo": "images/salah.png"
},
{
    "name": "Jadon Sancho",
    "team": "images/chelsea.png",
    "nationality": "images/anglie.webp",
    "rating": 85,
    "pace": 82,
    "shooting": 79,
    "passing": 80,
    "dribbling": 87,
    "defending": 43,
    "physicality": 74,
    "position": "RW",
    "photo": "images/sancho.png"
},


{
    "name": "Luka Modrić",
    "team": "images/real1.svg",
    "nationality": "images/croatia.webp",
    "rating": 89,
    "pace": 69,
    "shooting": 78,
    "passing": 89,
    "dribbling": 85,
    "defending": 57,
    "physicality": 68,
    "position": "CM",
    "photo": "images/modric.webp"
},


{
    "name": "Joshua Kimmich",
    "team": "images/bayern.png",
    "nationality": "images/germany.png",
    "rating": 88,
    "pace": 70,
    "shooting": 80,
    "passing": 88,
    "dribbling": 82,
    "defending": 84,
    "physicality": 75,
    "position": "CM",
    "photo": "images/kimmich.webp"
},

{
    "name": "Martin Ødegaard",
    "team": "images/arsenal.webp", 
    "nationality": "images/norsko.png",
    "rating": 87,
    "pace": 76,
    "shooting": 80,
    "passing": 89,
    "dribbling": 88,
    "defending": 60,
    "physicality": 68,
    "position": "CM",
    "photo": "images/odegard.png" 
},
{
    "name": "Jude Bellingham",
    "team": "images/real1.svg",
    "nationality": "images/anglie.webp",
    "rating": 87,
    "pace": 78,
    "shooting": 82,
    "passing": 84,
    "dribbling": 86,
    "defending": 75,
    "physicality": 81,
    "position": "CM",
    "photo": "images/belingham.png"
},
{
    "name": "Pedri",
    "team": "images/barca.png",
    "nationality": "images/spain.webp", 
    "rating": 86,
    "pace": 81,
    "shooting": 74,
    "passing": 86,
    "dribbling": 89,
    "defending": 72,
    "physicality": 68,
    "position": "CM",
    "photo": "images/pedri.png"   
},

{
    "name": "Virgil van Dijk",
    "team": "images/liverpool.webp",
    "nationality": "images/ned.webp",
    "rating": 90,
    "pace": 75,
    "shooting": 60,
    "passing": 75,
    "dribbling": 71,
    "defending": 92,
    "physicality": 85,
    "position": "CB",
    "photo": "images/dijk.png"
},
{
    "name": "Ruben Dias",
    "team": "images/city.png",
    "nationality": "images/portugal.png",
    "rating": 88,
    "pace": 70,
    "shooting": 55,
    "passing": 78,
    "dribbling": 65,
    "defending": 90,
    "physicality": 82,
    "position": "CB",
    "photo": "images/dias.png"
},
{
    "name": "William Saliba",
    "team": "images/arsenal.webp",
    "nationality": "images/francie.png",
    "rating": 86,
    "pace": 80,
    "shooting": 45,
    "passing": 74,
    "dribbling": 72,
    "defending": 88,
    "physicality": 85,
    "position": "CB",
    "photo": "images/saliba.png"
},

{
    "name": "Antonio Rudiger",
    "team": "images/real1.svg",
    "nationality": "images/germany.png",
    "rating": 85,
    "pace": 78,
    "shooting": 50,
    "passing": 72,
    "dribbling": 66,
    "defending": 87,
    "physicality": 83,
    "position": "CB",
    "photo": "images/rudiger.png"
},
{
    "name": "Achraf Hakimi",
    "team": "images/psg.png",
    "nationality": "images/maroko.png",
    "rating": 88,
    "pace": 92,
    "shooting": 75,
    "passing": 78,
    "dribbling": 80,
    "defending": 76,
    "physicality": 74,
    "position": "RB",
    "photo": "images/hakimi.png"
},
{
    "name": " Alexander-Arnold",
    "team": "images/liverpool.webp",
    "nationality": "images/anglie.webp",
    "rating": 87,
    "pace": 80,
    "shooting": 76,
    "passing": 82,
    "dribbling": 83,
    "defending": 75,
    "physicality": 72,
    "position": "RB",
    "photo": "images/arnold.png"
},
{
    "name": "João Cancelo",
    "team": "images/bayern.png",
    "nationality": "images/portugal.png",
    "rating": 86,
    "pace": 83,
    "shooting": 75,
    "passing": 80,
    "dribbling": 82,
    "defending": 78,
    "physicality": 74,
    "position": "RB",
    "photo": "images/cancelo.png"
},
{
    "name": "Andrew Robertson",
    "team": "images/liverpool.webp",
    "nationality": "images/scotland.png",
    "rating": 87,
    "pace": 81,
    "shooting": 72,
    "passing": 78,
    "dribbling": 81,
    "defending": 79,
    "physicality": 73,
    "position": "LB",
    "photo": "images/robertson.png"
},
{
    "name": "Theo Hernández",
    "team": "images/milan.png",
    "nationality": "images/francie.png",
    "rating": 86,
    "pace": 91,
    "shooting": 74,
    "passing": 77,
    "dribbling": 83,
    "defending": 80,    
    "physicality": 74,
    "position": "LB",
    "photo": "images/theo.png"
},
{
    "name": "Luke Shaw",
    "team": "images/utd.png",
    "nationality": "images/anglie.webp",
    "rating": 85,
    "pace": 78,
    "shooting": 72,
    "passing": 74,
    "dribbling": 78,
    "defending": 80,
    "physicality": 79,
    "position": "LB",
    "photo": "images/shaw.png"
},
{
    "name": "Thibaut Courtois",
    "team": "images/real1.svg",
    "nationality": "images/belgie.jpg",
    "rating": 92,
    "div": 93,
    "han": 85,
    "kic": 88,
    "ref": 86,
    "spd": 50,
    "pos": 89,
    "position": "GK",
    "photo": "images/courtois.png"
},
{
    "name": "Jan Oblak",
    "team": "images/atletico.png",
    "nationality": "images/slovinsko.png",
    "rating": 91,
    "div": 91,
    "han": 90,
    "kic": 89,
    "ref": 92,
    "spd": 48,
    "pos": 87,
    "position": "GK",
    "photo": "images/oblak.png"
},

{
    "name": "Alisson Becker",
    "team": "images/liverpool.webp",
    "nationality": "images/brazil.png",
    "rating": 91,
    "div": 89,
    "han": 90,
    "kic": 86,
    "ref": 88,
    "spd": 58,
    "pos": 83,
    "position": "GK",
    "photo": "images/alisson.png"
}

    ];